# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1310, 658)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-chat-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_menu = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_menu.sizePolicy().hasHeightForWidth())
        self.left_menu.setSizePolicy(sizePolicy)
        self.left_menu.setMinimumSize(QtCore.QSize(180, 640))
        self.left_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.left_menu.setStyleSheet("QWidget#left_sub_menu{\n"
"    opacity: 1.0;\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QFrame {\n"
"    border: 2px solid white; \n"
"    border-radius: 15px; \n"
"    background-color: rgb(149, 255, 149);\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 0;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QComboBox{\n"
"    color: rgb(0, 170, 0);\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.left_menu.setObjectName("left_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_menu)
        self.verticalLayout.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.left_sub_menu = QtWidgets.QWidget(parent=self.left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_sub_menu.sizePolicy().hasHeightForWidth())
        self.left_sub_menu.setSizePolicy(sizePolicy)
        self.left_sub_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.left_sub_menu.setStyleSheet("")
        self.left_sub_menu.setObjectName("left_sub_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_sub_menu)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.left_sub_menu)
        self.frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(145, 50))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.home_btn = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.home_btn.setFont(font)
        self.home_btn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons8-home-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_btn.setIcon(icon1)
        self.home_btn.setIconSize(QtCore.QSize(30, 30))
        self.home_btn.setFlat(True)
        self.home_btn.setObjectName("home_btn")
        self.horizontalLayout_4.addWidget(self.home_btn)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.left_sub_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(145, 50))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.menu_btn = QtWidgets.QComboBox(parent=self.frame_2)
        self.menu_btn.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.menu_btn.setFont(font)
        self.menu_btn.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.menu_btn.setStyleSheet("")
        self.menu_btn.setEditable(False)
        self.menu_btn.setObjectName("menu_btn")
        self.menu_btn.addItem("")
        self.menu_btn.addItem("")
        self.menu_btn.addItem("")
        self.menu_btn.addItem("")
        self.verticalLayout_3.addWidget(self.menu_btn)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_7 = QtWidgets.QFrame(parent=self.left_sub_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(145, 60))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.dmc_btn = QtWidgets.QComboBox(parent=self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.dmc_btn.setFont(font)
        self.dmc_btn.setObjectName("dmc_btn")
        self.dmc_btn.addItem("")
        self.dmc_btn.addItem("")
        self.dmc_btn.addItem("")
        self.verticalLayout_7.addWidget(self.dmc_btn)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(parent=self.left_sub_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(145, 60))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.translate_btn = QtWidgets.QPushButton(parent=self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.translate_btn.setFont(font)
        self.translate_btn.setFlat(True)
        self.translate_btn.setObjectName("translate_btn")
        self.horizontalLayout_6.addWidget(self.translate_btn)
        self.verticalLayout_2.addWidget(self.frame_6)
        spacerItem = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(parent=self.left_sub_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(145, 50))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settings_btn = QtWidgets.QPushButton(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.settings_btn.setFont(font)
        self.settings_btn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icons8-chat-settings-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_btn.setIcon(icon2)
        self.settings_btn.setIconSize(QtCore.QSize(30, 30))
        self.settings_btn.setFlat(True)
        self.settings_btn.setObjectName("settings_btn")
        self.horizontalLayout_2.addWidget(self.settings_btn)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.left_sub_menu)
        self.horizontalLayout.addWidget(self.left_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(1105, 600))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_page.sizePolicy().hasHeightForWidth())
        self.main_page.setSizePolicy(sizePolicy)
        self.main_page.setMinimumSize(QtCore.QSize(1100, 600))
        self.main_page.setObjectName("main_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main = QtWidgets.QWidget(parent=self.main_page)
        self.main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setMinimumSize(QtCore.QSize(1100, 630))
        self.main.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main.setObjectName("main")
        self.gridLayout = QtWidgets.QGridLayout(self.main)
        self.gridLayout.setObjectName("gridLayout")
        self.user_input = QtWidgets.QLineEdit(parent=self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_input.sizePolicy().hasHeightForWidth())
        self.user_input.setSizePolicy(sizePolicy)
        self.user_input.setMinimumSize(QtCore.QSize(950, 60))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        self.user_input.setFont(font)
        self.user_input.setStyleSheet("QLineEdit {\n"
"    border: 3px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.user_input.setFrame(True)
        self.user_input.setClearButtonEnabled(False)
        self.user_input.setObjectName("user_input")
        self.gridLayout.addWidget(self.user_input, 1, 0, 1, 1)
        self.send = QtWidgets.QPushButton(parent=self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send.sizePolicy().hasHeightForWidth())
        self.send.setSizePolicy(sizePolicy)
        self.send.setMinimumSize(QtCore.QSize(100, 60))
        self.send.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.send.setFont(font)
        self.send.setStyleSheet("QPushButton{\n"
"border: 3px solid white; \n"
"border-radius: 20px; \n"
"padding: 10px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}")
        self.send.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icons8-sent-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send.setIcon(icon3)
        self.send.setIconSize(QtCore.QSize(30, 30))
        self.send.setFlat(True)
        self.send.setObjectName("send")
        self.gridLayout.addWidget(self.send, 1, 1, 1, 1)
        self.main_text = QtWidgets.QTextBrowser(parent=self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_text.sizePolicy().hasHeightForWidth())
        self.main_text.setSizePolicy(sizePolicy)
        self.main_text.setMinimumSize(QtCore.QSize(1070, 540))
        self.main_text.setStyleSheet("QTextBrowser {\n"
"    border: 3px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 255, 0);\n"
"}")
        self.main_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.main_text.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.main_text.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.main_text.setPlaceholderText("")
        self.main_text.setObjectName("main_text")
        self.gridLayout.addWidget(self.main_text, 0, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.main)
        self.stackedWidget.addWidget(self.main_page)
        self.translation_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translation_page.sizePolicy().hasHeightForWidth())
        self.translation_page.setSizePolicy(sizePolicy)
        self.translation_page.setMinimumSize(QtCore.QSize(1100, 630))
        self.translation_page.setObjectName("translation_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.translation_page)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.translate = QtWidgets.QWidget(parent=self.translation_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate.sizePolicy().hasHeightForWidth())
        self.translate.setSizePolicy(sizePolicy)
        self.translate.setMinimumSize(QtCore.QSize(1100, 630))
        self.translate.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.translate.setObjectName("translate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.translate)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.translate)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.debug_from = QtWidgets.QTextEdit(parent=self.frame_4)
        self.debug_from.setStyleSheet("QTextEdit {\n"
"    border: 3px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 255, 0);    \n"
"    font: 700 14pt \"Cascadia Code\";\n"
"}")
        self.debug_from.setObjectName("debug_from")
        self.verticalLayout_5.addWidget(self.debug_from)
        self.submit_code_btn = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.submit_code_btn.setFont(font)
        self.submit_code_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}")
        self.submit_code_btn.setObjectName("submit_code_btn")
        self.verticalLayout_5.addWidget(self.submit_code_btn)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.translate)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.debug_to = QtWidgets.QTextEdit(parent=self.frame_5)
        self.debug_to.setStyleSheet("QTextEdit {\n"
"    border: 3px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(0, 255, 0);\n"
"    font: 700 14pt \"Cascadia Code\";\n"
"}")
        self.debug_to.setReadOnly(True)
        self.debug_to.setObjectName("debug_to")
        self.verticalLayout_6.addWidget(self.debug_to)
        self.copy_code_btn = QtWidgets.QPushButton(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(14)
        font.setBold(True)
        self.copy_code_btn.setFont(font)
        self.copy_code_btn.setStyleSheet("QPushButton{\n"
"    border: 3px solid white; \n"
"    border-radius: 20px; \n"
"    padding: 10px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}")
        self.copy_code_btn.setObjectName("copy_code_btn")
        self.verticalLayout_6.addWidget(self.copy_code_btn)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_5.addWidget(self.translate)
        self.stackedWidget.addWidget(self.translation_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chatbot"))
        self.home_btn.setText(_translate("MainWindow", "Home"))
        self.label.setText(_translate("MainWindow", "Mode"))
        self.menu_btn.setCurrentText(_translate("MainWindow", "-Select-"))
        self.menu_btn.setItemText(0, _translate("MainWindow", "-Select-"))
        self.menu_btn.setItemText(1, _translate("MainWindow", "Q&A"))
        self.menu_btn.setItemText(2, _translate("MainWindow", "Doctor"))
        self.menu_btn.setItemText(3, _translate("MainWindow", "Friend"))
        self.label_2.setText(_translate("MainWindow", "DMC"))
        self.dmc_btn.setItemText(0, _translate("MainWindow", "-Select-"))
        self.dmc_btn.setItemText(1, _translate("MainWindow", "DMC"))
        self.dmc_btn.setItemText(2, _translate("MainWindow", "Syllabus"))
        self.translate_btn.setText(_translate("MainWindow", "Debug"))
        self.settings_btn.setText(_translate("MainWindow", "Settings"))
        self.user_input.setPlaceholderText(_translate("MainWindow", "💬 Enter text here "))
        self.debug_from.setPlaceholderText(_translate("MainWindow", "Enter Code here"))
        self.submit_code_btn.setText(_translate("MainWindow", "Submit"))
        self.debug_to.setPlaceholderText(_translate("MainWindow", "Improved and Debugged code will appear here"))
        self.copy_code_btn.setText(_translate("MainWindow", "Copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
